### ISSUE TITLE
Allow us to customise the command name used in the description

### ISSUE THREAD

**Issue by adamtomat** [nunomaduro/laravel-console-summary#14]
## Current behaviour

When you run the `SummaryCommand`, the following line is output:

```
USAGE: westworld <command> [options] [arguments]
```

_Note that I'll use westworld as a placeholder for our app name for simplicity._

The name of the command (in this case, `westworld`) is dictated by the `ARTISAN_BINARY` constant (https://github.com/nunomaduro/laravel-console-summary/blob/78a618eae51d480b36e0ffce26905d9afafc219d/src/Describer.php#L67)

## Problem description and feature request

In our use-case the `ARTISAN_BINARY` is different to what our users actually need to run. We have a bash-script that would be named `westworld` (in this example) that proxies the PHP script called `westworld-php` used by Laravel Zero.

Our users need to run `westworld <command> [options] [arguments]`, but the summary outputs `westworld-php <command> [options] [arguments]`.

Thanks to how well written this & Laravel Zero is, we are able to write our own SummaryCommand and overwrite the `Describer`'s `describeUsage()` method - but that's a lot of overhead and is a little fragile.

Are you open to tweaking `Describe.php` to use a config variable to get the binary name rather than a constant?

For example:

```php
    /**
     * Describes the application title.
     *
     * @param  \Symfony\Component\Console\Output\OutputInterface  $output
     * @return \NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract
     */
    protected function describeUsage(OutputInterface $output): DescriberContract
    {
        $binary = config('artisan_binary', ARTISAN_BINARY);
        $output->write("  <fg=yellow;options=bold>USAGE:</> $binary <command> [options] [arguments]\n");

        return $this;
    }
 ```
 
 Open to other approaches too. We can also put an MR in for this too if it's something you're open to.
 
 Let me know your thoughts!

**Comment by owenvoke** [comment]
I'd be happy with this as an approach. 👍🏻 Not sure what @nunomaduro thinks, but I can see this being pretty useful for some people. 👌🏻
