### ISSUE TITLE
Changing the config publishing group?

### ISSUE THREAD

**Issue by emmadesilva** [nunomaduro/laravel-console-summary#17]
Hey! Thanks for all the amazing packages you've made! I just wanted to ask about something first before creating a PR, just in case the current behaviour is intentional.

I think the key used for publishing the package's config file should be updated to specify what it belongs to this package. Right now, when running `artisan vendor:publish` it just says `Tag: config` which doesn't mean much on its own. I think it should be `laravel-console-summary-config` or similar, to match the name of the published file.

This is the line I'm referring to: [`LaravelConsoleSummaryServiceProvider.php#L31`](https://github.com/nunomaduro/laravel-console-summary/blob/master/src/LaravelConsoleSummaryServiceProvider.php#L31)

**Comment by owenvoke** [comment]
Feel free to PR this change. 👍🏻
