### ISSUE TITLE
A feature request to "mute" unused commands?

### ISSUE THREAD

**Issue by librevlad** [nunomaduro/laravel-console-summary#5]
Hi! Not sure if Issues is the right place for feature requests, but let's try. I came across this package and it immediately became a must-have on my list - Artisan looks a little bit cleaner.

What I'm suggesting may also clean it up a lot. What if we had a way to optionally hide certain commands from the list via config file? Would be nice to get rid of some default commands on the list while still keeping them working. Is it technically possible?

**Comment by nunomaduro** [comment]
It's sounds good for me. Yes it's possible.

Can you work in a pull request for this?

**Comment by librevlad** [comment]
Will do!

чт, 11 апр. 2019 г., 10:34 Nuno Maduro <notifications@github.com>:

**Comment by librevlad** [comment]
I would also like to add an option to list all commands, something like --all, but this requires updating the contract's `describe` method signature, which breaks any potential user extensions of that contract.
